# Rebuild references from source, including removal of obsolete generated topics.
paths <- c(
  file.path(
    "packages",
    paste0(
      "dataraft.",
      c(
        "core",
        "lake",
        "adapters",
        "metrics",
        "dbt",
        "ide"
      )
    )
  ),
  "."
)
for (path in paths) {
  man <- file.path(path, "man")
  files <- list.files(man, pattern = "[.]Rd$", full.names = TRUE)
  generated <- vapply(
    files,
    function(file) {
      identical(
        readLines(file, n = 1L),
        "% Generated by roxygen2: do not edit by hand"
      )
    },
    logical(1)
  )
  unlink(files[generated])
  command <- sprintf(
    "roxygen2::roxygenise(%s)",
    encodeString(normalizePath(path, winslash = "/"), quote = '"')
  )
  status <- withr::with_envvar(
    c(R_LIBS = paste(.libPaths(), collapse = .Platform$path.sep)),
    system2(
      file.path(R.home("bin"), "R"),
      c("--vanilla", "--slave", "-e", shQuote(command))
    )
  )
  if (status != 0L) stop("Documentation failed: ", path)
}
